apiVersion: v1
kind: Service
metadata:
  name: banias-frontend
  labels:
    name: banias-frontend
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8081
  selector:
    app: banias-frontend

