apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: banias-frontend
  namespace: monitoring
  labels:
    k8s-app: banias-frontend
spec:
  selector:
    matchLabels:
      k8s-app: banias-frontend
  endpoints:
  - port: prom-metrics
    interval: 10s
  namespaceSelector:
    matchNames:
    - default
    - monitoring